language: node_js
node_js:
  - "0.12"
  - "stable"

before_install:
  # - "npm install -g npm@1.4.26"
  - "npm config set loglevel error"

before_script:
  - "npm install js2coffee@0.3.5 mocha@2.0.0 mkdirp@0.4.0 jdb@0.4.0 -g"
  - "npm install js2coffee@0.3.5 mocha@2.0.0 mkdirp@0.4.0 jdb@0.4.0 -D"
  - "npm i . -g"
  - "ls"
  - "ls dist/"

notifications:
  email: false

cahce:
    npm
