language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"

before_install:
  - "npm config set loglevel error"

post_install:
  - "npm install js2coffee@0.3.5 mocha@2.0.0 mkdirp@0.4.0 jdb@0.4.0 -g"
  - "npm install js2coffee@0.3.5 mocha@2.0.0 mkdirp@0.4.0 jdb@0.4.0 -D"
  - "npm i . -g"
