build: false

environment:
  matrix:
    - nodejs_version: "0.10"

install:
  - npm config set loglevel error
  - npm install
  - npm install nofs@0.4.0 lodash@2.4.1 coffee-script@1.8.0 mocha bluebird@2.9.0
  - npm install nokit nofs@0.4.0 lodash@2.4.1 coffee-script@1.8.0 mocha bluebird@2.9.0 -g
  - npm i . -g

test_script:
  - node --version
  - npm --version
  - npm test
