build: false

environment:
  matrix:
    - nodejs_version: "0.10"

install:
  - npm config set loglevel error
  - npm install
  - npm install js2coffee@0.3.5 mocha@2.0.0 mkdirp@0.4.0 jdb@0.4.0 -D
  - npm install js2coffee@0.3.5 mocha@2.0.0 mkdirp@0.4.0 jdb@0.4.0 -g
  - npm i . -g

test_script:
  - node --version
  - npm --version
  - npm test
