#---------------------------------#
#      general configuration      #
#---------------------------------#
branches:
  only:
    - master
  except:
    - gh-pages

skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#
shallow_clone: true

clone_depth: 1

environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 8

install:
  - ps: Install-Product node $env:nodejs_version
  - npm config set loglevel error
  - npm install
  - npm install js2coffee@0.3.5 mocha@2.0.0 mkdirp@0.4.0 jdb@0.4.0 @ysmood/material-ui -D
  - npm install js2coffee@0.3.5 mocha@2.0.0 mkdirp@0.4.0 jdb@0.4.0 @ysmood/material-ui -g
  - npm i . -g

#---------------------------------#
#       build configuration       #
#---------------------------------#
build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test_script:
  - node --version
  - npm --version
  - npm test
